server:
  port: 8002
  http2:
    # 启用 HTTP/2 支持，提升传输效率
    enabled: true
  compression:
    # 启用 GZIP 压缩，减少传输数据量
    enabled: true
    # 需要压缩的 MIME 类型
    mime-types: text/html, text/xml, text/plain, application/json
    # 最小压缩响应大小（字节）
  undertow:
    websockets:
      buffer-pool:
        direct: false  # 是否使用直接内存
        buffer-size: 1024  # 每个缓冲区大小
        max-pool-size: 2048  # 最大池大小

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/callcenter
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: 192.168.2.15
      port: 6379
      password: 123456
      database: 0
      timeout: 5000
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 30
          # 连接池最大阻塞等待时间（毫秒），负值表示没有限制
          max-wait: -1
          # 连接池中的最大空闲连接数
          max-idle: 20
          # 连接池中的最小空闲连接数
          min-idle: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        #format_sql: true
        dialect:
        session_factory:
  rabbitmq:
    host: 192.168.2.15
    port: 5672
    username: admin
    password: admin

nfs:
  path:
    base: /home/user/nfs/

xxl:
  job:
    admin:
      addresses: http://localhost:8080/xxl-job-admin
      accessToken: 7ab70f61dfd7d8c0f41b55e407254113
    executor:
      appname: dispatch-server
      ip: 127.0.0.1
      port: 8001